site_name: MAD at Freeletics
site_url: https://freeletics.github.io/freeletics-mad/
repo_name: MAD Freeletics
repo_url: https://github.com/freeletics/freeletics-mad
site_description: "Modern Android Development the Freeletics way"
site_author: Freeletics
remote_branch: gh-pages

copyright: 'Copyright &copy; 2021 Freeletics.'

theme:
  name: 'material'
  favicon: images/icon-freeletics.png
  logo: images/icon-freeletics.png
  palette:
    primary: 'black'
    accent: 'white'

extra_css:
  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - tables
