name: Publish Docs

on:
  push:
    branches:
      - main

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Android SDK
        run: ./.github/android-sdk.sh

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Build docs
        run: ./gradlew dokkaGfm

      - name: Copy docs
        run: |
          cp README.md docs/index.md
          cp navigator/README.md docs/navigator.md
          mkdir -p docs/Javadoc/navigator
          cp -R navigator/runtime/build/dokka/gfm/. docs/Javadoc/navigator/
          mkdir -p docs/Javadoc/navigator-compose
          cp -R navigator/runtime-compose/build/dokka/gfm/. docs/Javadoc/navigator-compose/
          mkdir -p docs/Javadoc/navigator-fragment
          cp -R navigator/runtime-fragment/build/dokka/gfm/. docs/Javadoc/navigator-fragment/
          mkdir -p docs/Javadoc/text-resource
          cp -R text-resource/build/dokka/gfm/. docs/Javadoc/text-resource/
          mkdir -p docs/Javadoc/state-machine
          cp -R state-machine/build/dokka/gfm/. docs/Javadoc/state-machine/

      - name: Deploy MkDocs
        run: |
          git fetch origin gh-pages:gh-pages
          mkdocs gh-deploy --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
